# config.py

import os

# FILE PATH
EXCEL_FILE_PATH  = os.getenv("EXCEL_FILE_PATH")
CSV_FILE_PATH = os.getenv("CSV_FILE_PATH")
DB_FILE_PATH = os.getenv("DB_FILE_PATH")
PARQUET_DATA_PATH = os.getenv("PARQUET_DATA_PATH")
PARQUET_CODE_PATH = os.getenv("PARQUET_CODE_PATH")
PARQUET_CODE_OUTPUT_PATH = os.getenv("PARQUET_CODE_OUTPUT_PATH")
PARQUET_OUTPUT_PATH = os.getenv("PARQUET_OUTPUT_PATH")
SEGMENT_PARQUET_PATH = os.getenv("SEGMENT_PARQUET_PATH")
FAMILY_PARQUET_PATH = os.getenv("FAMILY_PARQUET_PATH")
CLASS_PARQUET_PATH = os.getenv("CLASS_PARQUET_PATH")

# API KEYS
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")

# CHAT STUFF
TRAILING_PATTERN = r"(\s?>\s?)+$"
JSON_FILE_PATTERN = r'```json\s*({.*?})\s*```'
SYSTEM_PROMPT = os.getenv("SYSTEM_PROMPT")